### ISSUE TITLE
Drop support for Python 3.3

### ISSUE THREAD

**Issue by Grumblesmith** [Netuitive/netuitive-statsd#25]
Python 3.3 is no longer supported by the Python core team. We should no longer check it and should add testing against Python 3.6.

**Comment by tombakerjr** [comment]
@Grumblesmith If 3.3 is no longer supported, should we update the tox.ini, readme, setup.py, and anywhere else that might mention 3.3 support?

**Comment by Grumblesmith** [comment]
We sure should.
